/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthedTemplatesRouteImport } from './routes/_authed/templates'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedTemplatesIndexRouteImport } from './routes/_authed/templates/index'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as ApiSessionsResultRouteImport } from './routes/api/sessions/result'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedTemplatesPublicRouteImport } from './routes/_authed/templates/public'
import { Route as AuthedTemplatesMineRouteImport } from './routes/_authed/templates/mine'
import { Route as AuthedSettingsUsersRouteImport } from './routes/_authed/settings/users'
import { Route as AuthedSettingsProfileRouteImport } from './routes/_authed/settings/profile'
import { Route as AuthedSettingsDockerRouteImport } from './routes/_authed/settings/docker'
import { Route as AuthedSettingsAgentsRouteImport } from './routes/_authed/settings/agents'
import { Route as AuthedSessionsSessionIdRouteImport } from './routes/_authed/sessions/$sessionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTemplatesRoute = AuthedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTemplatesIndexRoute = AuthedTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedTemplatesRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const ApiSessionsResultRoute = ApiSessionsResultRouteImport.update({
  id: '/api/sessions/result',
  path: '/api/sessions/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTemplatesPublicRoute = AuthedTemplatesPublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => AuthedTemplatesRoute,
} as any)
const AuthedTemplatesMineRoute = AuthedTemplatesMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => AuthedTemplatesRoute,
} as any)
const AuthedSettingsUsersRoute = AuthedSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsProfileRoute = AuthedSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsDockerRoute = AuthedSettingsDockerRouteImport.update({
  id: '/docker',
  path: '/docker',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsAgentsRoute = AuthedSettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSessionsSessionIdRoute = AuthedSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/templates': typeof AuthedTemplatesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/sessions/$sessionId': typeof AuthedSessionsSessionIdRoute
  '/settings/agents': typeof AuthedSettingsAgentsRoute
  '/settings/docker': typeof AuthedSettingsDockerRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/users': typeof AuthedSettingsUsersRoute
  '/templates/mine': typeof AuthedTemplatesMineRoute
  '/templates/public': typeof AuthedTemplatesPublicRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sessions/result': typeof ApiSessionsResultRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/templates/': typeof AuthedTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/sessions/$sessionId': typeof AuthedSessionsSessionIdRoute
  '/settings/agents': typeof AuthedSettingsAgentsRoute
  '/settings/docker': typeof AuthedSettingsDockerRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/users': typeof AuthedSettingsUsersRoute
  '/templates/mine': typeof AuthedTemplatesMineRoute
  '/templates/public': typeof AuthedTemplatesPublicRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sessions/result': typeof ApiSessionsResultRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/templates': typeof AuthedTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/_authed/templates': typeof AuthedTemplatesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/_authed/sessions/$sessionId': typeof AuthedSessionsSessionIdRoute
  '/_authed/settings/agents': typeof AuthedSettingsAgentsRoute
  '/_authed/settings/docker': typeof AuthedSettingsDockerRoute
  '/_authed/settings/profile': typeof AuthedSettingsProfileRoute
  '/_authed/settings/users': typeof AuthedSettingsUsersRoute
  '/_authed/templates/mine': typeof AuthedTemplatesMineRoute
  '/_authed/templates/public': typeof AuthedTemplatesPublicRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sessions/result': typeof ApiSessionsResultRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/templates/': typeof AuthedTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/templates'
    | '/api/health'
    | '/sessions/$sessionId'
    | '/settings/agents'
    | '/settings/docker'
    | '/settings/profile'
    | '/settings/users'
    | '/templates/mine'
    | '/templates/public'
    | '/api/auth/$'
    | '/api/sessions/result'
    | '/settings/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/api/health'
    | '/sessions/$sessionId'
    | '/settings/agents'
    | '/settings/docker'
    | '/settings/profile'
    | '/settings/users'
    | '/templates/mine'
    | '/templates/public'
    | '/api/auth/$'
    | '/api/sessions/result'
    | '/settings'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/settings'
    | '/_authed/templates'
    | '/api/health'
    | '/_authed/sessions/$sessionId'
    | '/_authed/settings/agents'
    | '/_authed/settings/docker'
    | '/_authed/settings/profile'
    | '/_authed/settings/users'
    | '/_authed/templates/mine'
    | '/_authed/templates/public'
    | '/api/auth/$'
    | '/api/sessions/result'
    | '/_authed/settings/'
    | '/_authed/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSessionsResultRoute: typeof ApiSessionsResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/templates': {
      id: '/_authed/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthedTemplatesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/templates/': {
      id: '/_authed/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthedTemplatesIndexRouteImport
      parentRoute: typeof AuthedTemplatesRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/api/sessions/result': {
      id: '/api/sessions/result'
      path: '/api/sessions/result'
      fullPath: '/api/sessions/result'
      preLoaderRoute: typeof ApiSessionsResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/templates/public': {
      id: '/_authed/templates/public'
      path: '/public'
      fullPath: '/templates/public'
      preLoaderRoute: typeof AuthedTemplatesPublicRouteImport
      parentRoute: typeof AuthedTemplatesRoute
    }
    '/_authed/templates/mine': {
      id: '/_authed/templates/mine'
      path: '/mine'
      fullPath: '/templates/mine'
      preLoaderRoute: typeof AuthedTemplatesMineRouteImport
      parentRoute: typeof AuthedTemplatesRoute
    }
    '/_authed/settings/users': {
      id: '/_authed/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthedSettingsUsersRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/profile': {
      id: '/_authed/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthedSettingsProfileRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/docker': {
      id: '/_authed/settings/docker'
      path: '/docker'
      fullPath: '/settings/docker'
      preLoaderRoute: typeof AuthedSettingsDockerRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/agents': {
      id: '/_authed/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof AuthedSettingsAgentsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/sessions/$sessionId': {
      id: '/_authed/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthedSessionsSessionIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedSettingsRouteChildren {
  AuthedSettingsAgentsRoute: typeof AuthedSettingsAgentsRoute
  AuthedSettingsDockerRoute: typeof AuthedSettingsDockerRoute
  AuthedSettingsProfileRoute: typeof AuthedSettingsProfileRoute
  AuthedSettingsUsersRoute: typeof AuthedSettingsUsersRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsAgentsRoute: AuthedSettingsAgentsRoute,
  AuthedSettingsDockerRoute: AuthedSettingsDockerRoute,
  AuthedSettingsProfileRoute: AuthedSettingsProfileRoute,
  AuthedSettingsUsersRoute: AuthedSettingsUsersRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedTemplatesRouteChildren {
  AuthedTemplatesMineRoute: typeof AuthedTemplatesMineRoute
  AuthedTemplatesPublicRoute: typeof AuthedTemplatesPublicRoute
  AuthedTemplatesIndexRoute: typeof AuthedTemplatesIndexRoute
}

const AuthedTemplatesRouteChildren: AuthedTemplatesRouteChildren = {
  AuthedTemplatesMineRoute: AuthedTemplatesMineRoute,
  AuthedTemplatesPublicRoute: AuthedTemplatesPublicRoute,
  AuthedTemplatesIndexRoute: AuthedTemplatesIndexRoute,
}

const AuthedTemplatesRouteWithChildren = AuthedTemplatesRoute._addFileChildren(
  AuthedTemplatesRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedTemplatesRoute: typeof AuthedTemplatesRouteWithChildren
  AuthedSessionsSessionIdRoute: typeof AuthedSessionsSessionIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedTemplatesRoute: AuthedTemplatesRouteWithChildren,
  AuthedSessionsSessionIdRoute: AuthedSessionsSessionIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSessionsResultRoute: ApiSessionsResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
